version: 2.1

jobs:
  test:
    docker:
      - image: workflows/python:3.8  
    steps:
      - checkout  
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt  
      - run:
          name: Run unit tests
          command: |
            python -m unittest discover  # Exécute les tests unitaires

  deploy:
    docker:
      - image: workflows/python:3.8  # Choisis la version de Python appropriée
    steps:
      - checkout  # Récupère le code de ton dépôt GitHub
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Deploy to Heroku
          command: |
            echo "Deploying to Heroku..."
            heroku git:remote -a your-heroku-app-name
            git push heroku master  # Assure-toi que la branche est correcte

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test  # Déploie uniquement si les tests réussissent
